### ISSUE TITLE
requirements.txt fails due to invalid packages

### ISSUE THREAD

**Issue by dhruvbaldawa** [udacity/CarND-TensorFlow-Lab#1]
https://github.com/Brok-Bucholtz/Ud-DL-L1/blob/master/assignment/requirements.txt#L11-L12

Also, Tensorflow can not be directly installed via `pip` so you need to include the instructions or relevant link to Tensorflow documentation

**Comment by Brok-Bucholtz** [comment]
Fixed in 6b355235cb934adcdf3e0e9c3bedba980d20a0fb
