### ISSUE TITLE
Latest docker image somehow has tensorflow 0.11

### ISSUE THREAD

**Issue by wrgrant** [udacity/CarND-TensorFlow-Lab#13]
I'm going through the Intro To TensorFlow lab and the call to 

```global_variables_initializer()```

fails as 0.11 is looking for ```initialize_all_variables()```

I see that pull request #7 correctly made these changes and specified the updated version of tensorflow, but when I check the version that showed up in the docker image I just pulled today, this is the result:

```tf.__version__```
```0.11.0```

**Comment by mvirgo** [comment]
I've now changed over the set-up instructions to refer to the [Term 1 Starter Kit](https://github.com/udacity/CarND-Term1-Starter-Kit) so that we only need to manage in one place - thanks for the note.
