### ISSUE TITLE
tf.global_variables_initializer() throws missing attribute error in Docker container

### ISSUE THREAD

**Issue by umeshpandey007** [udacity/CarND-TensorFlow-Lab#16]
When running the lab.ipynb with the docker image(udacity/carnd-tensorflow-lab), tf.global_variables_initializer throws missing attribute error. However, replacing it with tf.initialize_all_variables works. 
I see that the change was done with the following commit:
update TensorFlow Variable initialization function commit f9c43461a9cd3d671d8ca445b53c9ed5cee237d1

Does that mean the tensorflow version in the docker image is old and does not supports global_variables_initializer?

**Comment by mvirgo** [comment]
I've now updated the repo to refer to the [Term 1 Starter Kit](https://github.com/udacity/CarND-Term1-Starter-Kit) so that we only need to keep this updated in one place - thanks for the note!
